version: '3.9'
services:
  tracking-app:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TZ=Asia/Kolkata
    command: 
      - /bin/bash
      - -c
      - |
        make run
        make run-web
    network_mode: "host"
    volumes:
      - .:/majordome
    
      
            
    